[features]
seeds = false
skip-lint = false
[programs.localnet]
decentralized_election = "EHTP9uMcGGMzXbUkShrSJ7e114gMnkW7nTWgvCQGmE2M"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/rohits/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
